config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  #get 'home/index'
  resources :emprunt_docs
  resources :empruntordis
  resources :ordinateurs
  resources :documents
  resources :auteurs
  resources :adherents
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/document.rb
class Document < ApplicationRecord
	belongs_to :auteur
	has_many :emprunt_docs, dependent: :delete_all
	#has_many :adherents, through: :emprunt_docs

	def self.search(search)
    if search
      document_resultat = Document.find_by(id: search)
        if document_resultat
          self.where(id: document_resultat)
        else
          @document = Document.all
        end
    else
      @document = Document.all
    end
  end

end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: %i[ show edit update destroy ]

  # GET /documents or /documents.json
  def index
    @documents = Document.search(params[:search])
  end

  # GET /documents/1 or /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents or /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to document_url(@document), notice: "Document was successfully created." }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1 or /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to document_url(@document), notice: "Document was successfully updated." }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1 or /documents/1.json
  def destroy
    @document.destroy

    respond_to do |format|
      format.html { redirect_to documents_url, notice: "Document was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def document_params
      params.require(:document).permit(:titre, :nombre_copies, :auteur_id, :search)
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= form_with(model: document) do |form| %>
  <% if document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
        <% document.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <%= form.label :titre %>
    <%= form.text_field :titre , class:"form-control", placeholder:"Titre"%>
  </div>

  <div class="field mb-3">
    <%= form.label :nombre_copies %>
    <%= form.number_field :nombre_copies , class:"form-control", placeholder:"Nombre de Copies"%>
  </div>

  <div class="field mb-3">
    <%= form.label :auteur_id %>
    <%= form.text_field :auteur_id , class:"form-control", placeholder:"ID de l'Auteur" %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing Document</h1>

<%= render 'form', document: @document %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Documents</h1>

<%= form_tag documents_path, :method => "get" do %>
<% label_tag(:search, "Quel est l'ID du document? ")  %>
<%= text_field_tag :search, params[:search] ,class:"form-control me-2", placeholder:"ID du Document" %>
<br>
<%= submit_tag("Rechercher", :id => nil , class:"btn btn-secondary") %>
<%end%>
<br>
<hr>
<br>
<table class="table table-hover table-striped table-bordered">
  <thead class="table-dark">
    <tr>
      <!--<th>ID</th>-->
      <th>Titre</th>
      <!--<th>Nombre copies</th>-->
      <th>Auteur</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <!--<td><% document.id %></td>-->
        <td><%= document.titre %></td>
        <!--<td><% document.nombre_copies %></td>-->
        <td><%= document.auteur.prenom %> <%= document.auteur.nom %></td>
        <td><%= link_to 'Détails', document, class:"btn btn-outline-primary btn-sm" %></td>
        <td><%= link_to 'Modifier', edit_document_path(document), class:"btn btn-outline-success btn-sm" %></td>
        <td><%= link_to 'Supprimer', document, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Document', new_document_path, class:"btn btn-secondary" %>

app/views/documents/new.html.erb
<h1>New Document</h1>

<%= render 'form', document: @document %>

<%= link_to 'Back', documents_path %>

app/views/documents/show.html.erb
<h2 align="center">Document <%= @document.id %> </h2>
<div class="mt-4 p-5 rounded bg-light ">
  
    <h5 class="display-5">
       <%= @document.titre %>
    </h5>

    <hr class="my-4">

    <p class="lead">
      <strong>ID:</strong>
      <%= @document.id %>
    </p>
    <p class="lead">
      <strong>Titre:</strong>
      <%= @document.titre %>
    </p>

    <p class="lead">
      <strong>Nombre de copies:</strong>
      <%= @document.nombre_copies %>
    </p>

    <p class="lead">
      <strong>Auteur:</strong>
      <%= @document.auteur.nom %> <%= @document.auteur.prenom %>
    </p>

  
    <%= link_to 'Modifier', edit_document_path(@document), class:"btn btn-secondary" %> 
    <%= link_to 'Supprimer', @document, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
    <%= link_to 'Retour', documents_path, class:"btn btn-dark" %>
  </div>