config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  #get 'home/index'
  resources :emprunt_docs
  resources :empruntordis
  resources :ordinateurs
  resources :documents
  resources :auteurs
  resources :adherents
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/adherent.rb
class Adherent < ApplicationRecord
  has_many :emprunt_docs, foreign_key: "adherent_id", dependent: :destroy
  has_many :documents, through: :emprunt_docs
  has_one :empruntordi , foreign_key: "adherent_id", dependent: :destroy
  has_one :ordinateur, through: :empruntordi


  def self.search(search)
    if search
      adherent_resultat = Adherent.find_by(id: search)
        if adherent_resultat
          self.where(id: adherent_resultat)
        else
          @adherent = Adherent.all
        end
    else
      @adherent = Adherent.all
    end
  end


end

app/controllers/adherents_controller.rb
class AdherentsController < ApplicationController
  before_action :set_adherent, only: %i[ show edit update destroy ]

  # GET /adherents or /adherents.json
  def index
    @adherents = Adherent.search(params[:search])
  end

  # GET /adherents/1 or /adherents/1.json
  def show
  end

  # GET /adherents/new
  def new
    @adherent = Adherent.new
  end

  # GET /adherents/1/edit
  def edit
  end

  # POST /adherents or /adherents.json
  def create
    @adherent = Adherent.new(adherent_params)

    respond_to do |format|
      if @adherent.save
        format.html { redirect_to adherent_url(@adherent), notice: "Adherent was successfully created." }
        format.json { render :show, status: :created, location: @adherent }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @adherent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adherents/1 or /adherents/1.json
  def update
    respond_to do |format|
      if @adherent.update(adherent_params)
        format.html { redirect_to adherent_url(@adherent), notice: "Adherent was successfully updated." }
        format.json { render :show, status: :ok, location: @adherent }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @adherent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adherents/1 or /adherents/1.json
  def destroy
    @adherent.destroy

    respond_to do |format|
      format.html { redirect_to adherents_url, notice: "Adherent was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_adherent
      @adherent = Adherent.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def adherent_params
      params.require(:adherent).permit(:nom, :prenom, :tel, :email, :search)
    end
end

app/helpers/adherents_helper.rb
module AdherentsHelper
end

app/views/adherents/_form.html.erb
<%= form_with(model: adherent) do |form| %>
  <% if adherent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(adherent.errors.count, "error") %> prohibited this adherent from being saved:</h2>

      <ul>
        <% adherent.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <%= form.label :nom %>
    <%= form.text_field :nom , class:"form-control", placeholder:"Nom"%>
  </div>

  <div class="field mb-3">
    <%= form.label :prenom %>
    <%= form.text_field :prenom , class:"form-control", placeholder:"Prenom"%>
  </div>

  <div class="field mb-3">
    <%= form.label :tel %>
    <%= form.text_field :tel, class:"form-control", placeholder:"Tel" %>
  </div>

  <div class="field mb-3">
    <%= form.label :email %>
    <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/adherents/edit.html.erb
<h1>Editing Adherent</h1>

<%= render 'form', adherent: @adherent %>
<br>
<%= link_to 'Détails', @adherent , class:"btn btn-outline-success btn-sm" %> 
<%= link_to 'Retour', adherents_path, class:"btn btn-outline-info btn-sm" %>

app/views/adherents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Adherents</h1>

<%= form_tag adherents_path,:method => "get" do %>
<% label_tag(:search, "Quel est l'ID de l'adherent? ")  %>
<%= text_field_tag :search, params[:search] ,class:"form-control me-2", placeholder:"ID de l'Adherent" %>
<br>
<%= submit_tag("Rechercher", :id => nil , class:"btn btn-secondary") %>
<%end%>
<br>
<hr>
<br>

<table class="table table-hover table-striped table-bordered">
  <thead class="table-dark">
    <tr>
      <th>Nom</th>
      <th>Prenom</th>
      <!--<th>Tel</th>-->
      <!--<th>Email</th>-->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @adherents.each do |adherent| %>
      <tr>
        <td><%= adherent.nom %></td>
        <td><%= adherent.prenom %></td>
        <!--<td><% adherent.tel %></td>-->
        <!--<td><% adherent.email %></td>-->
        <td><%= link_to 'Détails', adherent , class:"btn btn-outline-primary btn-sm"%></td>
        <td><%= link_to 'Modifier', edit_adherent_path(adherent), class:"btn btn-outline-success btn-sm" %></td>
        <td><%= link_to 'Supprimer', adherent, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Ajouter un Adherent', new_adherent_path , class:"btn btn-secondary"%>

app/views/adherents/new.html.erb
<h1>New Adherent</h1>

<%= render 'form', adherent: @adherent %>

<%= link_to 'Back', adherents_path %>

app/views/adherents/show.html.erb
<h2 align="center">Adherent <%= @adherent.id %> </h2>
<div class="mt-4 p-5 rounded bg-light ">
  
    <h5 class="display-5">
       <%= @adherent.nom %>
       <%= @adherent.prenom %>
    </h5>

    <hr class="my-4">

    <p class="lead">
      <strong>ID:</strong>
      <%= @adherent.id %>
    </p>
    <p class="lead">
      <strong>Nom:</strong>
      <%= @adherent.nom %>
    </p>

    <p class="lead">
      <strong>Prenom:</strong>
      <%= @adherent.prenom %>
    </p>

    <p class="lead">
      <strong>Tel:</strong>
      <%= @adherent.tel %>
    </p>

    <p class="lead">
      <strong>Email:</strong>
      <%= @adherent.email %>
    </p>
    
    <%= link_to 'Modifier', edit_adherent_path(@adherent), class:"btn btn-secondary" %> 
    <%= link_to 'Supprimer', @adherent, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
    <%= link_to 'Retour', adherents_path, class:"btn btn-dark" %>
  </div>