config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  #get 'home/index'
  resources :emprunt_docs
  resources :empruntordis
  resources :ordinateurs
  resources :documents
  resources :auteurs
  resources :adherents
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ordinateur.rb
class Ordinateur < ApplicationRecord
	has_one :empruntordi

	def self.search(search)
    if search
      ordinateur_resultat = Ordinateur.find_by(id: search)
        if ordinateur_resultat
          self.where(id: ordinateur_resultat)
        else
          @ordinateur = Ordinateur.all
        end
    else
      @ordinateur = Ordinateur.all
    end
  end


end

app/controllers/ordinateurs_controller.rb
class OrdinateursController < ApplicationController
  before_action :set_ordinateur, only: %i[ show edit update destroy ]

  # GET /ordinateurs or /ordinateurs.json
  def index
    @ordinateurs = Ordinateur.search(params[:search])
  end

  # GET /ordinateurs/1 or /ordinateurs/1.json
  def show
  end

  # GET /ordinateurs/new
  def new
    @ordinateur = Ordinateur.new
  end

  # GET /ordinateurs/1/edit
  def edit
  end

  # POST /ordinateurs or /ordinateurs.json
  def create
    @ordinateur = Ordinateur.new(ordinateur_params)

    respond_to do |format|
      if @ordinateur.save
        format.html { redirect_to ordinateur_url(@ordinateur), notice: "Ordinateur was successfully created." }
        format.json { render :show, status: :created, location: @ordinateur }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ordinateur.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ordinateurs/1 or /ordinateurs/1.json
  def update
    respond_to do |format|
      if @ordinateur.update(ordinateur_params)
        format.html { redirect_to ordinateur_url(@ordinateur), notice: "Ordinateur was successfully updated." }
        format.json { render :show, status: :ok, location: @ordinateur }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ordinateur.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ordinateurs/1 or /ordinateurs/1.json
  def destroy
    @ordinateur.destroy

    respond_to do |format|
      format.html { redirect_to ordinateurs_url, notice: "Ordinateur was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ordinateur
      @ordinateur = Ordinateur.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ordinateur_params
      params.require(:ordinateur).permit(:marque, :nbr_copies, :search)
    end
end

app/helpers/ordinateurs_helper.rb
module OrdinateursHelper
end

app/views/ordinateurs/_form.html.erb
<%= form_with(model: ordinateur) do |form| %>
  <% if ordinateur.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ordinateur.errors.count, "error") %> prohibited this ordinateur from being saved:</h2>

      <ul>
        <% ordinateur.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <%= form.label :marque %>
    <%= form.text_field :marque, class:"form-control", placeholder:"Marque" %>
  </div>

  <div class="field mb-3">
    <%= form.label :nbr_copies %>
    <%= form.number_field :nbr_copies , class:"form-control", placeholder:"Nombre de Copies"%>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/ordinateurs/edit.html.erb
<h1>Editing Ordinateur</h1>

<%= render 'form', ordinateur: @ordinateur %>

<%= link_to 'Show', @ordinateur %> |
<%= link_to 'Back', ordinateurs_path %>

app/views/ordinateurs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ordinateurs</h1>

<%= form_tag ordinateurs_path, :method => "get" do %>
<% label_tag(:search, "Quel est l'ID de l'ordinateur? ")  %>
<%= text_field_tag :search, params[:search] ,class:"form-control me-2", placeholder:"ID de l'Ordinateur" %>
<br>
<%= submit_tag("Rechercher", :id => nil , class:"btn btn-secondary") %>
<%end%>
<br>
<hr>
<br>
<table class="table table-hover table-striped table-bordered">
  <thead class="table-dark">
    <tr>
      <th>Marque</th>
      <th>Nbr copies</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ordinateurs.each do |ordinateur| %>
      <tr>
        <td><%= ordinateur.marque %></td>
        <td><%= ordinateur.nbr_copies %></td>
        <td><%= link_to 'Détails', ordinateur, class:"btn btn-outline-primary btn-sm" %></td>
        <td><%= link_to 'Modifier', edit_ordinateur_path(ordinateur), class:"btn btn-outline-success btn-sm" %></td>
        <td><%= link_to 'Supprimer', ordinateur, method: :delete, data: { confirm: 'Are you sure?' } , class:"btn btn-outline-danger btn-sm"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ordinateur', new_ordinateur_path, class:"btn btn-secondary" %>

app/views/ordinateurs/new.html.erb
<h1>New Ordinateur</h1>

<%= render 'form', ordinateur: @ordinateur %>

<%= link_to 'Back', ordinateurs_path %>

app/views/ordinateurs/show.html.erb
<h2 align="center">Ordinateur <%= @ordinateur.id %> </h2>
<div class="mt-4 p-5 rounded bg-light ">
  
    <h5 class="display-5">
       Ordinateur <%= @ordinateur.marque %> <%= @ordinateur.id %> 
    </h5>

    <hr class="my-4">

    <p class="lead">
      <strong>ID:</strong>
      <%= @ordinateur.id %>
    </p>
    <p class="lead">
      <strong>Marque:</strong>
      <%= @ordinateur.marque %>
    </p>

    <p class="lead">
      <strong>Nbr copies:</strong>
      <%= @ordinateur.nbr_copies %>
    </p>
  
    <%= link_to 'Modifier', edit_ordinateur_path(@ordinateur), class:"btn btn-secondary" %> 
    <%= link_to 'Supprimer', @ordinateur, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
    <%= link_to 'Retour', ordinateurs_path, class:"btn btn-dark" %>
  </div>